### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by wjt**
Currently, `npm outdated` shows the following:

```
Package          Current  Wanted  Latest  Location                      Depended by
@actions/github    4.0.0   4.0.0   6.0.0  node_modules/@actions/github  godot-asset-lib-action
@vercel/ncc       0.27.0  0.27.0  0.38.1  node_modules/@vercel/ncc      godot-asset-lib-action
axios             0.21.4  0.21.4   1.7.2  node_modules/axios            godot-asset-lib-action
prettier           2.8.8   2.8.8   3.3.2  node_modules/prettier         godot-asset-lib-action
```

`npm audit` shows:

```
# npm audit report

axios  0.8.1 - 0.27.2
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix --force`
Will install axios@1.7.2, which is a breaking change
node_modules/axios

1 moderate severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force
```

`@actions/core` is pinned to an old minor version, causing a warning to be logged on each run:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

And `actions.yml` specifies the `node12` runtime, which has been unsupported since summer 2023: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

This PR updates all dependencies to their latest versions (including new semver major versions); and updates the actions runtime to `node20`.

Stacked on:

- #4 
- #5

### CODE REVIEW

**Comment by wjt** [comment]
I have marked this as a draft because, while I've tested the code locally with `node index.js` and a bunch of environment variables set to fake the GitHub Actions environment, I have not tested it in the real GitHub Actions environment.

**Comment by wjt** [comment]
It was surprising to me to find that the generated code is checked into the repository. (But Node is not my usual toolchain.)

I opted to update `dist/` all at once in a single commit at the end of the series but I can also fold it into each commit.

**Comment by wjt** [comment]
I have successfully published a new release of our plugin using this branch.

**Comment by dploeger** [comment]
@wjt I've merged the other PRs now. Is this still required? I was confused by all the PRs. 😄

**Comment by wjt** [comment]
It's still desirable. I'll rebase this to fix conflicts and ping you when ready.

**Comment by wjt** [comment]
This one is ready to go now. As described it updates the Node.JS runtime that the action uses, and also updates all the action's dependencies to their latest releases.

**Review by dploeger — APPROVED** [review]
Awesome. Thanks! 🎁

**Pull request merged**
